/**
* mobilegateway API generated from mobilegateway.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


#pragma once


#include "../base/ArpTableBase.h"


class Mobilegateway;

using namespace polycube::service::model;

struct arp_entry {
  uint64_t mac;
  uint32_t port;
} __attribute__((packed));

class ArpTable : public ArpTableBase {
 public:
  ArpTable(Mobilegateway &parent, const ArpTableJsonObject &conf);
  ArpTable(Mobilegateway &parent, const std::string &mac, const std::string &ip,
          const std::string &interface);
  virtual ~ArpTable();

  /// <summary>
  /// Destination IP address
  /// </summary>
  std::string getAddress() override;

  /// <summary>
  /// Destination MAC address
  /// </summary>
  std::string getMac() override;
  void setMac(const std::string &value) override;

  /// <summary>
  /// Outgoing interface
  /// </summary>
  std::string getInterface() override;
  void setInterface(const std::string &value) override;

private:
  std::string mac_;
  std::string ip_;
  std::string interface_;
};
