/**
* mobilegateway API generated from mobilegateway.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


// TODO: Modify these methods with your own implementation


#include "BaseStation.h"
#include "Mobilegateway.h"


BaseStation::BaseStation(Mobilegateway &parent, const BaseStationJsonObject &conf)
    : BaseStationBase(parent) {
  ip_ = conf.getIp();

  // Check that the base station can be reached from a UE port
  std::string port = parent_.search_interface_from_nexthop(ip_);
  if (parent_.getPorts(port)->getDirection() != PortsDirectionEnum::UE) {
    throw std::runtime_error("The base station must be reachable from a UE port");
  }
}

BaseStation::~BaseStation() {}

std::string BaseStation::getIp() {
  return ip_;
}


