/**
* mobilegateway API generated from mobilegateway.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


#pragma once


#include "../base/BaseStationBase.h"


class Mobilegateway;

using namespace polycube::service::model;

class BaseStation : public BaseStationBase {
 public:
  BaseStation(Mobilegateway &parent, const BaseStationJsonObject &conf);
  virtual ~BaseStation();

  /// <summary>
  /// IP address of the Base Station
  /// </summary>
  std::string getIp() override;

 private:
  std::string ip_;
};
