/**
* mobilegateway API generated from mobilegateway.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/

#pragma once

#include "../base/PortsSecondaryipBase.h"

class Ports;

using namespace polycube::service::model;

class PortsSecondaryip : public PortsSecondaryipBase {
 public:
  PortsSecondaryip(Ports &parent, const PortsSecondaryipJsonObject &conf);
  virtual ~PortsSecondaryip();

  /// <summary>
  /// Secondary IP address and prefix of the port
  /// </summary>
  std::string getIp() override;

  // The following methods have been added manually

  static void createInControlPlane(Ports &parent, const std::string &ip,
                                   const PortsSecondaryipJsonObject &conf);

  bool operator<(const PortsSecondaryip &p) const {
    return std::tie(ip_) < std::tie(p.ip_);
  }

 private:
  // The following variables have been added manually
  std::string ip_;
};
