/**
* redirect API generated from redirect.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* RedirectApi.h
*
*/

#pragma once

#define POLYCUBE_SERVICE_NAME "redirect"


#include "polycube/services/response.h"
#include "polycube/services/shared_lib_elements.h"

#include "PortsJsonObject.h"
#include "RedirectJsonObject.h"
#include <vector>


#ifdef __cplusplus
extern "C" {
#endif

Response create_redirect_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response create_redirect_ports_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response create_redirect_ports_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response delete_redirect_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response delete_redirect_ports_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response delete_redirect_ports_list_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_redirect_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_redirect_list_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_redirect_ports_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_redirect_ports_list_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response replace_redirect_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response replace_redirect_ports_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response replace_redirect_ports_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_redirect_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_redirect_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_redirect_ports_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_redirect_ports_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);

Response redirect_list_by_id_help(const char *name, const Key *keys, size_t num_keys);
Response redirect_ports_list_by_id_help(const char *name, const Key *keys, size_t num_keys);


#ifdef __cplusplus
}
#endif

