/**
* policer API generated from policer.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */



#include "DefaultContractUpdateDataInputJsonObject.h"
#include <regex>

namespace polycube {
namespace service {
namespace model {

DefaultContractUpdateDataInputJsonObject::DefaultContractUpdateDataInputJsonObject() {
  m_actionIsSet = false;
  m_rateLimitIsSet = false;
}

DefaultContractUpdateDataInputJsonObject::DefaultContractUpdateDataInputJsonObject(const nlohmann::json &val) :
  JsonObjectBase(val) {
  m_actionIsSet = false;
  m_rateLimitIsSet = false;


  if (val.count("action")) {
    setAction(string_to_ActionTypeEnum(val.at("action").get<std::string>()));
  }

  if (val.count("rate-limit")) {
    setRateLimit(val.at("rate-limit").get<uint64_t>());
  }
}

nlohmann::json DefaultContractUpdateDataInputJsonObject::toJson() const {
  nlohmann::json val = nlohmann::json::object();
  if (!getBase().is_null()) {
    val.update(getBase());
  }

  if (m_actionIsSet) {
    val["action"] = ActionTypeEnum_to_string(m_action);
  }

  if (m_rateLimitIsSet) {
    val["rate-limit"] = m_rateLimit;
  }

  return val;
}

ActionTypeEnum DefaultContractUpdateDataInputJsonObject::getAction() const {
  return m_action;
}

void DefaultContractUpdateDataInputJsonObject::setAction(ActionTypeEnum value) {
  m_action = value;
  m_actionIsSet = true;
}

bool DefaultContractUpdateDataInputJsonObject::actionIsSet() const {
  return m_actionIsSet;
}

void DefaultContractUpdateDataInputJsonObject::unsetAction() {
  m_actionIsSet = false;
}

std::string DefaultContractUpdateDataInputJsonObject::ActionTypeEnum_to_string(const ActionTypeEnum &value){
  switch(value) {
    case ActionTypeEnum::PASS:
      return std::string("pass");
    case ActionTypeEnum::LIMIT:
      return std::string("limit");
    case ActionTypeEnum::DROP:
      return std::string("drop");
    default:
      throw std::runtime_error("Bad DefaultContractUpdateDataInput action");
  }
}

ActionTypeEnum DefaultContractUpdateDataInputJsonObject::string_to_ActionTypeEnum(const std::string &str){
  if (JsonObjectBase::iequals("pass", str))
    return ActionTypeEnum::PASS;
  if (JsonObjectBase::iequals("limit", str))
    return ActionTypeEnum::LIMIT;
  if (JsonObjectBase::iequals("drop", str))
    return ActionTypeEnum::DROP;
  throw std::runtime_error("DefaultContractUpdateDataInput action is invalid");
}
uint64_t DefaultContractUpdateDataInputJsonObject::getRateLimit() const {
  return m_rateLimit;
}

void DefaultContractUpdateDataInputJsonObject::setRateLimit(uint64_t value) {
  m_rateLimit = value;
  m_rateLimitIsSet = true;
}

bool DefaultContractUpdateDataInputJsonObject::rateLimitIsSet() const {
  return m_rateLimitIsSet;
}

void DefaultContractUpdateDataInputJsonObject::unsetRateLimit() {
  m_rateLimitIsSet = false;
}


}
}
}

