/**
* policer API generated from policer.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */



#include "DefaultContractJsonObject.h"
#include <regex>

namespace polycube {
namespace service {
namespace model {

DefaultContractJsonObject::DefaultContractJsonObject() {
  m_action = ActionTypeEnum::PASS;
  m_actionIsSet = true;
  m_rateLimitIsSet = false;
}

DefaultContractJsonObject::DefaultContractJsonObject(const nlohmann::json &val) :
  JsonObjectBase(val) {
  m_actionIsSet = false;
  m_rateLimitIsSet = false;


  if (val.count("action")) {
    setAction(string_to_ActionTypeEnum(val.at("action").get<std::string>()));
  }

  if (val.count("rate-limit")) {
    setRateLimit(val.at("rate-limit").get<uint64_t>());
  }
}

nlohmann::json DefaultContractJsonObject::toJson() const {
  nlohmann::json val = nlohmann::json::object();
  if (!getBase().is_null()) {
    val.update(getBase());
  }

  if (m_actionIsSet) {
    val["action"] = ActionTypeEnum_to_string(m_action);
  }

  if (m_rateLimitIsSet) {
    val["rate-limit"] = m_rateLimit;
  }

  return val;
}

ActionTypeEnum DefaultContractJsonObject::getAction() const {
  return m_action;
}

void DefaultContractJsonObject::setAction(ActionTypeEnum value) {
  m_action = value;
  m_actionIsSet = true;
}

bool DefaultContractJsonObject::actionIsSet() const {
  return m_actionIsSet;
}

void DefaultContractJsonObject::unsetAction() {
  m_actionIsSet = false;
}

std::string DefaultContractJsonObject::ActionTypeEnum_to_string(const ActionTypeEnum &value){
  switch(value) {
    case ActionTypeEnum::PASS:
      return std::string("pass");
    case ActionTypeEnum::LIMIT:
      return std::string("limit");
    case ActionTypeEnum::DROP:
      return std::string("drop");
    default:
      throw std::runtime_error("Bad DefaultContract action");
  }
}

ActionTypeEnum DefaultContractJsonObject::string_to_ActionTypeEnum(const std::string &str){
  if (JsonObjectBase::iequals("pass", str))
    return ActionTypeEnum::PASS;
  if (JsonObjectBase::iequals("limit", str))
    return ActionTypeEnum::LIMIT;
  if (JsonObjectBase::iequals("drop", str))
    return ActionTypeEnum::DROP;
  throw std::runtime_error("DefaultContract action is invalid");
}
uint64_t DefaultContractJsonObject::getRateLimit() const {
  return m_rateLimit;
}

void DefaultContractJsonObject::setRateLimit(uint64_t value) {
  m_rateLimit = value;
  m_rateLimitIsSet = true;
}

bool DefaultContractJsonObject::rateLimitIsSet() const {
  return m_rateLimitIsSet;
}

void DefaultContractJsonObject::unsetRateLimit() {
  m_rateLimitIsSet = false;
}


}
}
}

