/**
* mobilegateway API generated from mobilegateway.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* BaseStationJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"


namespace polycube {
namespace service {
namespace model {


/// <summary>
///
/// </summary>
class  BaseStationJsonObject : public JsonObjectBase {
public:
  BaseStationJsonObject();
  BaseStationJsonObject(const nlohmann::json &json);
  ~BaseStationJsonObject() final = default;
  nlohmann::json toJson() const final;


  /// <summary>
  /// IP address of the Base Station
  /// </summary>
  std::string getIp() const;
  void setIp(std::string value);
  bool ipIsSet() const;

private:
  std::string m_ip;
  bool m_ipIsSet;
};

}
}
}

