/**
* mobilegateway API generated from mobilegateway.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */



#include "PortsJsonObject.h"
#include <regex>

namespace polycube {
namespace service {
namespace model {

PortsJsonObject::PortsJsonObject() {
  m_nameIsSet = false;
  m_ipIsSet = false;
  m_secondaryipIsSet = false;
  m_macIsSet = false;
  m_direction = PortsDirectionEnum::PDN;
  m_directionIsSet = true;
}

PortsJsonObject::PortsJsonObject(const nlohmann::json &val) :
  JsonObjectBase(val) {
  m_nameIsSet = false;
  m_ipIsSet = false;
  m_secondaryipIsSet = false;
  m_macIsSet = false;
  m_directionIsSet = false;


  if (val.count("name")) {
    setName(val.at("name").get<std::string>());
  }

  if (val.count("ip")) {
    setIp(val.at("ip").get<std::string>());
  }

  if (val.count("secondaryip")) {
    for (auto& item : val["secondaryip"]) {
      PortsSecondaryipJsonObject newItem{ item };
      m_secondaryip.push_back(newItem);
    }

    m_secondaryipIsSet = true;
  }

  if (val.count("mac")) {
    setMac(val.at("mac").get<std::string>());
  }

  if (val.count("direction")) {
    setDirection(string_to_PortsDirectionEnum(val.at("direction").get<std::string>()));
  }
}

nlohmann::json PortsJsonObject::toJson() const {
  nlohmann::json val = nlohmann::json::object();
  if (!getBase().is_null()) {
    val.update(getBase());
  }

  if (m_nameIsSet) {
    val["name"] = m_name;
  }

  if (m_ipIsSet) {
    val["ip"] = m_ip;
  }

  {
    nlohmann::json jsonArray;
    for (auto& item : m_secondaryip) {
      jsonArray.push_back(JsonObjectBase::toJson(item));
    }

    if (jsonArray.size() > 0) {
      val["secondaryip"] = jsonArray;
    }
  }

  if (m_macIsSet) {
    val["mac"] = m_mac;
  }

  if (m_directionIsSet) {
    val["direction"] = PortsDirectionEnum_to_string(m_direction);
  }

  return val;
}

std::string PortsJsonObject::getName() const {
  return m_name;
}

void PortsJsonObject::setName(std::string value) {
  m_name = value;
  m_nameIsSet = true;
}

bool PortsJsonObject::nameIsSet() const {
  return m_nameIsSet;
}



std::string PortsJsonObject::getIp() const {
  return m_ip;
}

void PortsJsonObject::setIp(std::string value) {
  m_ip = value;
  m_ipIsSet = true;
}

bool PortsJsonObject::ipIsSet() const {
  return m_ipIsSet;
}

void PortsJsonObject::unsetIp() {
  m_ipIsSet = false;
}

const std::vector<PortsSecondaryipJsonObject>& PortsJsonObject::getSecondaryip() const{
  return m_secondaryip;
}

void PortsJsonObject::addPortsSecondaryip(PortsSecondaryipJsonObject value) {
  m_secondaryip.push_back(value);
  m_secondaryipIsSet = true;
}


bool PortsJsonObject::secondaryipIsSet() const {
  return m_secondaryipIsSet;
}

void PortsJsonObject::unsetSecondaryip() {
  m_secondaryipIsSet = false;
}

std::string PortsJsonObject::getMac() const {
  return m_mac;
}

void PortsJsonObject::setMac(std::string value) {
  m_mac = value;
  m_macIsSet = true;
}

bool PortsJsonObject::macIsSet() const {
  return m_macIsSet;
}

void PortsJsonObject::unsetMac() {
  m_macIsSet = false;
}

PortsDirectionEnum PortsJsonObject::getDirection() const {
  return m_direction;
}

void PortsJsonObject::setDirection(PortsDirectionEnum value) {
  m_direction = value;
  m_directionIsSet = true;
}

bool PortsJsonObject::directionIsSet() const {
  return m_directionIsSet;
}

void PortsJsonObject::unsetDirection() {
  m_directionIsSet = false;
}

std::string PortsJsonObject::PortsDirectionEnum_to_string(const PortsDirectionEnum &value){
  switch(value) {
    case PortsDirectionEnum::UE:
      return std::string("ue");
    case PortsDirectionEnum::PDN:
      return std::string("pdn");
    default:
      throw std::runtime_error("Bad Ports direction");
  }
}

PortsDirectionEnum PortsJsonObject::string_to_PortsDirectionEnum(const std::string &str){
  if (JsonObjectBase::iequals("ue", str))
    return PortsDirectionEnum::UE;
  if (JsonObjectBase::iequals("pdn", str))
    return PortsDirectionEnum::PDN;
  throw std::runtime_error("Ports direction is invalid");
}

}
}
}

