/**
* redirect API generated from redirect.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */



#include "RedirectJsonObject.h"
#include <regex>

namespace polycube {
namespace service {
namespace model {

RedirectJsonObject::RedirectJsonObject() {
  m_nameIsSet = false;
  m_portsIsSet = false;
}

RedirectJsonObject::RedirectJsonObject(const nlohmann::json &val) :
  JsonObjectBase(val) {
  m_nameIsSet = false;
  m_portsIsSet = false;


  if (val.count("name")) {
    setName(val.at("name").get<std::string>());
  }

  if (val.count("ports")) {
    for (auto& item : val["ports"]) {
      PortsJsonObject newItem{ item };
      m_ports.push_back(newItem);
    }

    m_portsIsSet = true;
  }
}

nlohmann::json RedirectJsonObject::toJson() const {
  nlohmann::json val = nlohmann::json::object();
  if (!getBase().is_null()) {
    val.update(getBase());
  }

  if (m_nameIsSet) {
    val["name"] = m_name;
  }

  {
    nlohmann::json jsonArray;
    for (auto& item : m_ports) {
      jsonArray.push_back(JsonObjectBase::toJson(item));
    }

    if (jsonArray.size() > 0) {
      val["ports"] = jsonArray;
    }
  }

  return val;
}

std::string RedirectJsonObject::getName() const {
  return m_name;
}

void RedirectJsonObject::setName(std::string value) {
  m_name = value;
  m_nameIsSet = true;
}

bool RedirectJsonObject::nameIsSet() const {
  return m_nameIsSet;
}



const std::vector<PortsJsonObject>& RedirectJsonObject::getPorts() const{
  return m_ports;
}

void RedirectJsonObject::addPorts(PortsJsonObject value) {
  m_ports.push_back(value);
  m_portsIsSet = true;
}


bool RedirectJsonObject::portsIsSet() const {
  return m_portsIsSet;
}

void RedirectJsonObject::unsetPorts() {
  m_portsIsSet = false;
}


}
}
}

