/**
* mobilegateway API generated from mobilegateway.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* BaseStationBase.h
*
*
*/

#pragma once

#include "../serializer/BaseStationJsonObject.h"






#include <spdlog/spdlog.h>

using namespace polycube::service::model;

class Mobilegateway;

class BaseStationBase {
 public:
  
  BaseStationBase(Mobilegateway &parent);
  
  virtual ~BaseStationBase();
  virtual void update(const BaseStationJsonObject &conf);
  virtual BaseStationJsonObject toJsonObject();

  /// <summary>
  /// IP address of the Base Station
  /// </summary>
  virtual std::string getIp() = 0;

  std::shared_ptr<spdlog::logger> logger();
 protected:
  Mobilegateway &parent_;
};
