/**
* mobilegateway API generated from mobilegateway.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "BaseStationBase.h"
#include "../Mobilegateway.h"


BaseStationBase::BaseStationBase(Mobilegateway &parent)
    : parent_(parent) {}

BaseStationBase::~BaseStationBase() {}

void BaseStationBase::update(const BaseStationJsonObject &conf) {

}

BaseStationJsonObject BaseStationBase::toJsonObject() {
  BaseStationJsonObject conf;

  conf.setIp(getIp());

  return conf;
}

std::shared_ptr<spdlog::logger> BaseStationBase::logger() {
  return parent_.logger();
}

