/**
* mobilegateway API generated from mobilegateway.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "PortsSecondaryipBase.h"
#include "../Mobilegateway.h"


PortsSecondaryipBase::PortsSecondaryipBase(Ports &parent)
    : parent_(parent) {}

PortsSecondaryipBase::~PortsSecondaryipBase() {}

void PortsSecondaryipBase::update(const PortsSecondaryipJsonObject &conf) {

}

PortsSecondaryipJsonObject PortsSecondaryipBase::toJsonObject() {
  PortsSecondaryipJsonObject conf;

  conf.setIp(getIp());

  return conf;
}

std::shared_ptr<spdlog::logger> PortsSecondaryipBase::logger() {
  return parent_.logger();
}

