/**
* mobilegateway API generated from mobilegateway.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "UserEquipmentBase.h"
#include "../Mobilegateway.h"


UserEquipmentBase::UserEquipmentBase(Mobilegateway &parent)
    : parent_(parent) {}

UserEquipmentBase::~UserEquipmentBase() {}

void UserEquipmentBase::update(const UserEquipmentJsonObject &conf) {

  if (conf.tunnelEndpointIsSet()) {
    setTunnelEndpoint(conf.getTunnelEndpoint());
  }
  if (conf.teidIsSet()) {
    setTeid(conf.getTeid());
  }
  if (conf.rateLimitIsSet()) {
    setRateLimit(conf.getRateLimit());
  }
}

UserEquipmentJsonObject UserEquipmentBase::toJsonObject() {
  UserEquipmentJsonObject conf;

  conf.setIp(getIp());
  conf.setTunnelEndpoint(getTunnelEndpoint());
  conf.setTeid(getTeid());
  conf.setRateLimit(getRateLimit());

  return conf;
}

std::shared_ptr<spdlog::logger> UserEquipmentBase::logger() {
  return parent_.logger();
}

