/**
* mobilegateway API generated from mobilegateway.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* UserEquipmentBase.h
*
*
*/

#pragma once

#include "../serializer/UserEquipmentJsonObject.h"






#include <spdlog/spdlog.h>

using namespace polycube::service::model;

class Mobilegateway;

class UserEquipmentBase {
 public:
  
  UserEquipmentBase(Mobilegateway &parent);
  
  virtual ~UserEquipmentBase();
  virtual void update(const UserEquipmentJsonObject &conf);
  virtual UserEquipmentJsonObject toJsonObject();

  /// <summary>
  /// IP address of the User Equipment
  /// </summary>
  virtual std::string getIp() = 0;

  /// <summary>
  /// IP address of the Base Station that connects the User Equipment
  /// </summary>
  virtual std::string getTunnelEndpoint() = 0;
  virtual void setTunnelEndpoint(const std::string &value) = 0;

  /// <summary>
  /// Tunnel Endpoint ID of the GTP tunnel used by the User Equipment
  /// </summary>
  virtual uint32_t getTeid() = 0;
  virtual void setTeid(const uint32_t &value) = 0;

  /// <summary>
  /// Rate limit for the traffic exchanged by the User Equipment (in bps)
  /// </summary>
  virtual uint64_t getRateLimit() = 0;
  virtual void setRateLimit(const uint64_t &value) = 0;

  std::shared_ptr<spdlog::logger> logger();
 protected:
  Mobilegateway &parent_;
};
