/**
* trafficclassifier API generated from trafficclassifier.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "TrafficclassifierBase.h"

TrafficclassifierBase::TrafficclassifierBase(const std::string name) {
  logger()->set_pattern("[%Y-%m-%d %H:%M:%S.%e] [Trafficclassifier] [%n] [%l] %v");
}



TrafficclassifierBase::~TrafficclassifierBase() {}

void TrafficclassifierBase::update(const TrafficclassifierJsonObject &conf) {
  set_conf(conf.getBase());

  if (conf.trafficClassIsSet()) {
    for (auto &i : conf.getTrafficClass()) {
      auto id = i.getId();
      auto m = getTrafficClass(id);
      m->update(i);
    }
  }
}

TrafficclassifierJsonObject TrafficclassifierBase::toJsonObject() {
  TrafficclassifierJsonObject conf;
  conf.setBase(to_json());

  conf.setName(getName());
  for(auto &i : getTrafficClassList()) {
    conf.addTrafficClass(i->toJsonObject());
  }

  return conf;
}
void TrafficclassifierBase::addTrafficClassList(const std::vector<TrafficClassJsonObject> &conf) {
  for (auto &i : conf) {
    uint32_t id_ = i.getId();
    addTrafficClass(id_, i);
  }
}

void TrafficclassifierBase::replaceTrafficClass(const uint32_t &id, const TrafficClassJsonObject &conf) {
  delTrafficClass(id);
  uint32_t id_ = conf.getId();
  addTrafficClass(id_, conf);
}

void TrafficclassifierBase::delTrafficClassList() {
  auto elements = getTrafficClassList();
  for (auto &i : elements) {
    uint32_t id_ = i->getId();
    delTrafficClass(id_);
  }
}


